# Generated by Django 2.2.2 on 2019-07-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(1, 'Active'), (2, 'inactive'), (3, 'pending')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applive.Base')),
                ('country_name', models.CharField(max_length=100)),
            ],
            bases=('applive.base',),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applive.Base')),
                ('language_name', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applive.Country')),
            ],
            bases=('applive.base',),
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applive.Base')),
                ('channel_name', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applive.Country')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applive.Language')),
            ],
            bases=('applive.base',),
        ),
    ]
