# Generated by Django 2.2.2 on 2019-07-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applive', '0002_auto_20190701_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='country_id',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='applive.Country'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='language_id',
            field=models.ForeignKey(db_column='language_id', on_delete=django.db.models.deletion.CASCADE, to='applive.Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='country_id',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='applive.Country'),
        ),
    ]
