# Generated by Django 2.2.2 on 2019-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applive', '0003_auto_20190701_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'inactive'), ('3', 'pending')], max_length=100),
        ),
    ]
