# Generated by Django 2.2.2 on 2019-07-23 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applive', '0004_auto_20190702_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='country',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='language',
            name='attachments',
        ),
        migrations.AddField(
            model_name='channels',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
