# Generated by Django 2.2.2 on 2019-07-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applive', '0005_auto_20190723_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channels',
            old_name='channel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='channels',
            old_name='channel_path',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language_name',
            new_name='name',
        ),
    ]
