# Generated by Django 2.2.2 on 2019-08-03 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applive', '0007_auto_20190725_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='status',
            field=models.CharField(choices=[('1', ((10, 'Active'), (20, 'YES'))), ('2', 'inactive'), ('3', 'pending')], max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='country_id',
            field=models.ForeignKey(db_column='country_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='applive.Country'),
        ),
    ]
