# Generated by Django 2.2.2 on 2019-08-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applive', '0008_auto_20190803_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'inactive'), ('3', 'pending')], max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='country_id',
            field=models.ForeignKey(db_column='country_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='applive.Country'),
            preserve_default=False,
        ),
    ]
